### PR TITLE
Target branch config change

### PR DESCRIPTION
**Pull request by badkk**

### CODE REVIEW

**Comment by badkk** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

:clock10: **Preparing**: average preparing time is _35 sec(s)_

**Comment by badkk** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

:clock10: **Incremental building**: average incremental building time is not available, there is no data for this repository.

**Comment by badkk** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[buildstrategytester/index.md](https://github.com/LucasDvp/buildstrategetester/blob/master-pr3/buildstrategytester/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/buildstrategytester/index?branch=pr-en-us-3) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C2%5C13%5Cae0da712-e91e-5233-6b4d-2d1dd18fac04%5CPullRequest%5C201902130544061941-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aBqKBDgcvX3elIteHWOTHwtEvDuSMIMmATf2l8c0%2FBg%3D&st=2019-02-13T05%3A40%3A05Z&se=2019-03-16T05%3A45%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by LucasDvp** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

:clock10: **Preparing**: average preparing time is _34 sec(s)_

**Comment by LucasDvp** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

:clock10: **Incremental building**: average incremental building time is _21 sec(s)_

**Comment by LucasDvp** [comment]
OPS Build status updates of commit _[1c0ec30](https://github.com/LucasDvp/buildstrategetester/pull/3/commits/1c0ec30ecdd73a0a1536174c5732043699ba7f1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[buildstrategytester/index.md](https://github.com/LucasDvp/buildstrategetester/blob/master-pr3/buildstrategytester/index.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/buildstrategytester/index?branch=pr-en-us-3) | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C2%5C13%5Cae0da712-e91e-5233-6b4d-2d1dd18fac04%5CPullRequest%5C201902130547189369-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=61Bo5WW414PyTqpRtTSTxGhhkGF%2Bs4R9wZfQPnLp0fI%3D&st=2019-02-13T05%3A43%3A08Z&se=2019-03-16T05%3A48%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
